namespace: ecommerce-system
image:
  repository: shubham379/ai-devops-project-web
  tag: "v1"
  pullPolicy: Always

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  host: ecommerce.local
  path: /
  ingressClassName: traefik

jwtSecret:
  # NOTE: For production, use --set or a secret management solution.
  value: change-me

persistence:
  enabled: true
  size: 1Gi
  storageClassName: ""
  hostPath: /tmp/ecommerce-data
  accessModes:
    - ReadWriteOnce

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60

networkPolicy:
  enabled: true

